### ISSUE TITLE
Why CSS classes appending :before with content?

### ISSUE THREAD

**Issue by isevcik** [jossef/material-design-icons-iconfont#53]
The style definition also defines compound classes like `.material-icons.done` which applies `:before` with `content : ` containing glyph code for the related icon.
This is unlike the original google/material-design-icons repo and could cause errors like duplicated icons (if you apply classes like `.done` for `<i>` for your own purposes).
The documentation or README says nothing about this divergence.

**Comment by flmuel** [comment]
There is a bug, when using the "material-icons-content" function. The function does not map the name to the font code. But the material-icon mixin uses this function too for "unquoting", so you have to edit both:

```scss
@mixin material-icon($name, $pseudo: 'before') {
  $codepoint: map-get($material-icons-codepoints, $name);

  &::#{$pseudo} {
    content: unquote('"\\#{$codepoint}"');
  }
}

@function material-icons-content($codepoint) {
  @return unquote('"\\#{map-get($material-icons-codepoints, $codepoint)}"');
}
```
